#+TITLE: Linear model

Unlike tree updater, we have lots of duplicated parameters in linear model.  We should remove these duplication by grouping them into a single `dmlc::Parameter` object.  But for now, we document them as it is.

* Table Of Content                                                      :TOC_8_gh:
- [[#gblinear][GBLinear]]
  - [[#gblineartrainparam][GBLinearTrainParam]]
  - [[#gblinearmodel][GBLinearModel]]
    - [[#gblinearmodelparam][GBLinearModelParam]]
  - [[#linearupdater][LinearUpdater]]
    - [[#coordinate-descent][Coordinate descent]]
      - [[#coordinatetrainparam][CoordinateTrainParam]]
    - [[#gpu-coordinate-descent][GPU Coordinate descent]]
      - [[#gpucoordinatetrainparam][GPUCoordinateTrainParam]]
    - [[#shotgun][Shotgun]]
      - [[#shotguntrainparam][ShotgunTrainParam]]

* GBLinear
GBLinear is the root object for boosting linear models.
#+BEGIN_SRC javascript
  {
      "GBLinearTrainParam": *GBLinearTrainParam*,

      "GBLinearModel": *GBLinearModel*,

      "updater": *LinearUpdater*,
  }
#+END_SRC
** GBLinearTrainParam
#+BEGIN_SRC javascript
  {
    "updater": "<updater-name>",
    "<updater-name>": *LinearUpdater*,

    "tolerance": *float*,
    "max_row_perbatch": *integer*
  }
#+END_SRC
** GBLinearModel
#+BEGIN_SRC javascript
  {
    "GBLinearModelParam": *GBLinearModelParam*,
    "weight": [*float*, ...]
  }
#+END_SRC
*** GBLinearModelParam
#+BEGIN_SRC javascript
  {
    "num_feature": *integer*,
    "num_output_group": *integer*
    // field `reserved` is not used.
  }
#+END_SRC

** LinearUpdater
*** Coordinate descent
**** CoordinateTrainParam
#+BEGIN_SRC javascript
  {
    "learning_rate": *float*,
    "reg_lambda": *reg_lambda*,
    "reg_alpha": *reg_alpha*,
    "feature_selector": *integer*,
    "top_k": *integer*,

    "reg_lambda_denorm": *integer*,
    "reg_alpha_denorm": *integer*
  }
#+END_SRC
*** GPU Coordinate descent
**** GPUCoordinateTrainParam
#+BEGIN_SRC javascript
  {
    "learning_rate": *float*,
    "reg_lambda": *reg_lambda*,
    "reg_alpha": *reg_alpha*,
    "feature_selector": *integer*,
    "top_k": *integer*,

    "reg_lambda_denorm": *integer*,
    "reg_alpha_denorm": *integer*
  }
#+END_SRC
*** Shotgun
**** ShotgunTrainParam
#+BEGIN_SRC javascript
  {
    "learning_rate": *float*,
    "reg_lambda": *float*,
    "reg_alpha": *float*,
    "feature_selector": *integer*,

    "reg_lambda_denorm": *integer*,
    "reg_alpha_denorm": *integer*
  }
#+END_SRC
#  LocalWords:  GPUCoordinateTrainParam LocalWords GBLinearTrainParam GBLinear
#  LocalWords:  GBLinearModel LinearUpdater CoordinateTrainParam
#  LocalWords:  ShotgunTrainParam GBLinearModelParam